In [ ]:
import numpy as np

In [3]:
#QUSTION:01
# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.standard_normal(15)
# Print the resulting array
print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[ 0.62367742  1.12230826 -1.74100246  0.38347676 -0.86548365 -0.05903495
 -0.33311476 -1.26075337  0.21510024 -0.85129789 -0.80783068 -0.12211588
 -0.82686814 -0.396146   -1.81848377]


In [4]:
#QUSTION:02
#  Create an array of all even integers from 30 to 70 using NumPy
even_integers_array = np.arange(30, 71, 2)
print("Array of all even integers from 30 to 70:")
print(even_integers_array)

Array of all even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
#QUESTION:03
#creating two matrices.
matrix1 = np.array([[3, 4], [8, 10]])
matrix2 = np.array([[5, 6], [11, 13]])
# Computing  matrix multiplication
result_matrix = np.dot(matrix1, matrix2)
# Now Print the result
print("Resultant Matrix:")
print(result_matrix)


Resultant Matrix:
[[ 59  70]
 [150 178]]


In [6]:
#QUESTION:04
# Defining square matrix
matrix = np.array([[2, 4], [7, 8]])
# Compute the determinant
determinant_value = np.linalg.det(matrix)
# Print the result
print("Determinant of the matrix:")
print(determinant_value)


Determinant of the matrix:
-12.0


In [2]:
#QUESTION:05
import numpy as np
# Creating  5x5 array with random values
random_array = np.random.rand(5, 5)
# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)
# Print the array and results
print("Random 5x5 array:")
print(random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Random 5x5 array:
[[0.13986186 0.43323035 0.59664645 0.78674909 0.09900641]
 [0.5516844  0.3882842  0.53069391 0.39687289 0.75353768]
 [0.71619495 0.74635544 0.75102522 0.5136477  0.84833613]
 [0.90859687 0.83174908 0.00883695 0.87608841 0.19618628]
 [0.2442213  0.05401582 0.89736476 0.60949417 0.88462223]]

Minimum value: 0.008836953906681488
Maximum value: 0.908596866078381


In [14]:
#QUESTION:06
# Creating a sample 2D array
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#mean along the second axis
mean_values = np.mean(sample_array, axis=1)
#standard deviation along the second axis
std_values = np.std(sample_array, axis=1)
#Compute variance along the second axis
variance_values = np.var(sample_array, axis=1)
#Print the results
print("Mean along the second axis:", mean_values)
print("Standard deviation along the second axis:", std_values)
print("Variance along the second axis:", variance_values)


Mean along the second axis: [2. 5. 8.]
Standard deviation along the second axis: [0.81649658 0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667 0.66666667]
